theme: jekyll-theme-architect

title: [Batch Lab]
description: [JSR352 Hands-on Lab]

links:
  #download: https://download_url/
  source: https://github.com/javaee/batchlab
  #docs: https://docs_url/
  #javadocs: https://javadoc_url/
  #faq: https://faq_url
  #mailinglist: https://faq_url/
